# Generated by Django 5.2.5 on 2025-09-08 07:56

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_account_user_alter_account_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
